### ISSUE TITLE
No plans to set a proxy setting?

### ISSUE THREAD

**Issue by jojonki** [ryanseys/node-gtoken#4]
I want to use your library under proxy environment. But I assume your code doesn't have proxy options currently. Do you have any plans to support proxy?
[your request module's code](https://github.com/ryanseys/node-gtoken/blob/master/lib/index.js#L199)

**Comment by ryanseys** [comment]
It uses the request npm module under the hood which allows you to set a
proxy via Environment variables. Check out the request documentation and
see if that helps. Let me know if you get stuck (sorry typing from my phone)

**Comment by jojonki** [comment]
Thank you for your advice. I've never known node's request module uses environment proxy settings. I'll check request modules' document.
